# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_FSL_LS1024A_PFE) += fsl_ls1024a_pfe.o
fsl_ls1024a_pfe-objs := pfe_platform.o pfe_hw.o pfe_hw_lib.o pfe_firmware.o pfe_hif.o pfe_hif_lib.o pfe_ctrl.o pfe_eth.o
